version: '3.8'
services:
  api:
    image: inf25dw1g10/api-horarios
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=Igor1234!
      - DB_NAME=school
    depends_on:
      - db

  db:
    image: inf25dw1g10/mysql-db
    restart: always
    ports:
      - "3306:3306"

